#!/bin/bash

#-----Globals-------
DIR="";
FOLDER_NAME="";
MONSTERS=();
OBJECTS=();

#------Source--------
source utils;
source player;
source monsters;
source objects;
source rooms;

#-----Functions------
init_game_loop()
{
	clear;
	echo $(to_runic "Welcome To Magicus");
	look;

	while true; do
		echo "";
		read -ep ">" COMMAND;
		echo "";
		process_command $COMMAND;
	done
}

restart()
{
	rm $PLAYER_PATH;
	rm $MONSTER_PATH;
	rm $OBJECT_PATH;

	init_files
	source $PLAYER_PATH;
	look;
}

process_command()
{
  if [ -z $1 ]; then return; fi

  if (( $HEALTH <= 0 )); then
    death $1
    return;
  fi

  LAST_COMMAND=$@;
  DIR_CHECK=$(cd $DIR && ls -p | grep '.\/' | grep -c $1);

  if [ "$1" = "look" ] || [ "$1" = "l" ]; then
    look;
  elif [ "$1" = "equip" ]; then
  	equip_object $2
  elif [ "$1" = "set" ]; then
    set_player_value $2 $3
  elif [ "$1" = "attack" ] || [ "$1" = "a" ] || [ "$1" = "att" ] || [ "$1" = "kill" ]; then
    attack_monster $@
  elif [ "$1" = "teleport" ]; then
    change_room $2;
  elif [ "$1" = "go" ]; then
    go_direction $2;
  elif [ "$(echo $1 | tr 'A-Z' 'a-z')" = "back" ]; then
    go_direction 'back';
  elif [ $DIR_CHECK -gt 0 ]; then
    go_direction $1;
  else
    echo "Sorry, I don't understand: $1";
  fi
}

#-------Execution------
source magicus.conf;
init_files
source $PLAYER_PATH;
change_room $SAVEDIR;
init_game_loop;
