#!/bin/bash

#-----Globals-------
DIR="";
FOLDER_NAME="";
MONSTERS=();
OBJECTS=();

#------Source--------
source utils;
source player;
source monsters;
source objects;
source rooms;
source spells;

#-----Functions------
init_game_loop()
{
  echo $(to_runic "Welcome To Magicus");
  clear;
	look;

  while true; do
    if (( $HEALTH <= 0 )); then
      echo "$NAME has been slain at level $LEVEL! Press return to create a new character"
      read -ep ">";
      restart
    else
		  echo "";
  		read -ep ">" command;
  		echo "";
  		process_command $command;
    fi
	done
}

restart()
{
	rm $PLAYER_PATH;
	rm $MONSTER_PATH;
	rm $OBJECT_PATH;

	init_files
	source $PLAYER_PATH;
	look;
}

process_command()
{
  if [ -z $1 ]; then echo "Nothing happens."; fi

  actions=("attack" "a" "equip" "e" "back" "go" "teleport");
  free_actions=("look" "l" "set");
  spells=("sana")

  if [[ "${actions[@]}" =~ "${1}" ]]; then
    process_action $@;
    return;
  fi

  if [[ "${free_actions[@]}" =~ "${1}" ]]; then
    process_free_action $@;
    return;
  fi

  if [[ "${spells[@]}" =~ "${1}" ]]; then
    process_spell $@;
    return;
  fi

  # Maybe can get rid of this if we change the names of the rooms
  is_command_directory=$(cd $DIR && ls -p | grep '.\/' | grep -c $1);
  if [ $is_command_directory -gt 0 ]; then
    go_direction $1;
    return;
  fi

  echo "Sorry, I don't understand $1";
}

process_action()
{
  case "$1" in
    attack|a)
      attack_monster $@;
    ;;

    equip|e)
      equip_object $2;
    ;;

    equip|e)
      equip_object $2;
    ;;

    teleport)
      change_room $2;
    ;;

    go)
      go_direction $2;
    ;;

    back)
      go_direction "back";
    ;;

    *);;
  esac

  load_monsters;
  defend;
  player_heartbeat;
}

process_free_action()
{
  case "$1" in
    look|l)
      look;
    ;;

    set)
      set_player_value $2 $3;
    ;;

    *);;
  esac
}

process_spell()
{
  case "$1" in
    sana|l)
      heal;
    ;;

    *);;
  esac
}

#-------Execution------
source magicus.conf;
init_files;
source $PLAYER_PATH;
change_room $SAVEDIR;
init_game_loop;
