#!/bin/bash
room_adjectives=("accessible" "adjoining" "airy" "ancient" "bare" "basic" "beautiful" "bright" "brilliant" "cavernous" "ceremonial" "clean" "colorful" "comfortable" "cozy" "damp" "dark" "decorated" "dingy" "dirty" "dismal" "dusty" "elegant" "enclosed" "enormous" "filthy" "fine" "functional" "furnished" "gilded" "gloomy" "grand" "haunted" "luxurious" "magnificent" "miserable" "modest" "ordinary" "oversize" "palatial" "panelled" "quaint" "rustic" "sacred" "shabby" "simple" "small" "smoky" "spacious" "spartan" "splendid" "spotless" "stately" "strange" "stuffy" "tidy" "tiny" "vaulted" "wretched");
vowels=("a" "e" "i" "o" "u");

get_room_adjective()
{
  local OBJECT_COUNT=$(cd $DIR && ls -p | grep -v / | grep -c -v '^\.');

  if [ $OBJECT_COUNT -gt 10 ]; then
    echo 'a packed';
  elif [ $OBJECT_COUNT -gt 5 ]; then
    echo 'a cluttered';
  elif [ $OBJECT_COUNT -eq 0 ]; then
    echo 'an empty';
  else
    room_adjective_index=$(rand 0 ${#room_adjectives[@]});
    room_adjective=${room_adjectives[$room_adjective_index]};
    first_letter=${room_adjective:0:1};
    adjective_prefix="a";

    if [[ "${vowels[@]}" =~ "$first_letter" ]]; then
      adjective_prefix="an";
    fi

    echo "$adjective_prefix $room_adjective";
  fi
}

list_exits()
{
  echo "Exits    : (Back) $(cd $DIR && ls -p | grep '.\/' | tr '\n' ' ' | sed 's/\///g')";
}

get_room_type()
{
  local PATH_COUNT=$(cd $DIR && ls -l | grep -c ^d);

  if [ $PATH_COUNT -eq 1 ]; then
    echo 'hallway';
  elif [ $PATH_COUNT -gt 1 ]; then
    echo 'corridor';
  else
    echo 'room';
  fi
}

go_direction()
{
  if [ "$1" = "back" ]; then
    if [ "$DIR" = "/" ]; then
      change_room "/";
    else
      change_room "$DIR/../";
    fi
    look;
  elif [ -z "$1" ]; then
    echo $(list_exits);
  else
    change_room $(echo "$DIR/$1" | sed 's|//|/|');
    look;
  fi
}

change_room()
{
  export DIR=$(cd $1 && pwd);
  set_player_value savedir $DIR;
  FOLDER_NAME="$(echo $DIR | sed 's/^\/$/Entrance Hall/g' | sed 's@.*/@@')";
  encounter_monsters
}
